// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResaleTelegramBot.Persistence.DbContexts;

#nullable disable

namespace ResaleTelegramBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251109162541_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.BuyerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("BuyerProfiles");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuyerProfileId");

                    b.HasIndex("ListingId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SellerProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerProfileId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.ListingPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("TelegramFileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingPhotos");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.SellerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("SellerProfiles");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.BuyerProfile", b =>
                {
                    b.HasOne("ResaleTelegramBot.Core.Models.User", "UserProfile")
                        .WithOne("BuyerProfile")
                        .HasForeignKey("ResaleTelegramBot.Core.Models.BuyerProfile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.Favorite", b =>
                {
                    b.HasOne("ResaleTelegramBot.Core.Models.BuyerProfile", "BuyerProfile")
                        .WithMany("Favorites")
                        .HasForeignKey("BuyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResaleTelegramBot.Core.Models.Listing", "Listing")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerProfile");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.Listing", b =>
                {
                    b.HasOne("ResaleTelegramBot.Core.Models.Category", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResaleTelegramBot.Core.Models.SellerProfile", "SellerProfile")
                        .WithMany("Listings")
                        .HasForeignKey("SellerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SellerProfile");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.ListingPhoto", b =>
                {
                    b.HasOne("ResaleTelegramBot.Core.Models.Listing", "Listing")
                        .WithMany("Photos")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.SellerProfile", b =>
                {
                    b.HasOne("ResaleTelegramBot.Core.Models.User", "UserProfile")
                        .WithOne("SellerProfile")
                        .HasForeignKey("ResaleTelegramBot.Core.Models.SellerProfile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.User", b =>
                {
                    b.OwnsOne("ResaleTelegramBot.Core.Shared.Models.TelegramData", "TelegramData", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Username")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("TelegramData")
                        .IsRequired();
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.BuyerProfile", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.Category", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.Listing", b =>
                {
                    b.Navigation("FavoritedBy");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.SellerProfile", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("ResaleTelegramBot.Core.Models.User", b =>
                {
                    b.Navigation("BuyerProfile")
                        .IsRequired();

                    b.Navigation("SellerProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
